### ISSUE TITLE
Feat: Add open-runtime example for `python-3.11` LTS

### ISSUE THREAD

**Issue by afzal442** [open-runtimes/open-runtimes#110]
Hi 👋🏻  @stnguyen90 @Meldiron 

Ref: https://www.python.org/downloads/release/python-3110/
https://github.com/docker-library/python/blob/f04b43cb1775d382587b0446717613fb912225a9/3.11/alpine3.16/Dockerfile

Any thoughts on this adding such? Thanks

**Comment by stnguyen90** [comment]
@afzal442, would you like to contribute this?

**Comment by afzal442** [comment]
Yes, I'm into it.

**Comment by stnguyen90** [comment]
@afzal442 Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by greendesertsnow** [comment]
hi, is there any progress on this ? 👯

**Comment by stnguyen90** [comment]
Closing as Python-3.11 is in open-runtimes now: https://github.com/open-runtimes/open-runtimes/tree/main/runtimes/python-3.11
