### ISSUE TITLE
Feature proposal: add support for more up-to-date Deno runtime

### ISSUE THREAD

**Issue by t0mm4rx** [open-runtimes/open-runtimes#170]
Hello,

Deno introduced the support for NPM packages in the 1.28 version. It makes the runtime way more powerful.

It would be great to implement a Deno runtime > 1.28 so we can use these new features. I don't think there is breaking change.

Also, what do you think about changing the default template to include types for the request and the response, such as:
```ts
import { sdk } from "./deps.ts";

interface Request {
  headers: { [key: string]: string };
  payload: string;
  variables: { [key: string]: string };
}

interface Response {
  send: (message: string, status: number) => void;
  json: (response: unknown, status: number) => void;
}

export default async function (req: Request, res: Response) {
  ...
}

```

I don't know if you work with external contributors, but I could get the job done.

**Comment by stnguyen90** [comment]
@t0mm4rx thanks for raising this. open-runtimes now has [deno 1.35](https://github.com/open-runtimes/open-runtimes/tree/main/runtimes/deno-1.35)!
