### ISSUE TITLE
Dart runtime stuck when uncaught error inside function occur

### ISSUE THREAD

**Issue by obiwanzenobi** [open-runtimes/open-runtimes#174]
Checked on 2.17 and 2.18, compared with node-18.0

Creating function with code:

```dart
Future<void> start(final req, final res) async {
  throw Exception('Not implemented');
}
```

will prevent dart runtime from sending ANY answer.

For comparison this code on node-18.0 will fail fast with proper (status 500) response:

```js
module.exports = async function (req, res) {
  throw new Error('Not implemented');
};
```

Expected behavior: dart runtime fails fast if any internal error is thrown

The problem could be here: 
https://github.com/open-runtimes/open-runtimes/blob/main/runtimes/dart-2.17/server.dart#L35
because of:
```
/// The zone will always be an error-zone ([Zone.errorZone]), so returning
/// a future created inside the zone, and waiting for it outside of the zone,
/// will risk the future not being seen to complete.
```

**Comment by lohanidamodar** [comment]
@obiwanzenobi It seems you are using one of the older runtimes, we recommend using `dart 2.18` which shouldn't have this issue. Also wait for upcoming release, we are working on adding dart 2.19 and dart 3.0 as well.

**Comment by JoshiJoshiJoshi** [comment]
Can it be updated to Dart 3.1 as well?

**Comment by stnguyen90** [comment]
Closing as the new version of open runtimes will return an error:

<img width="1040" alt="image" src="https://github.com/open-runtimes/open-runtimes/assets/1477010/7ce9d51a-9e99-4ed7-b120-cc4ef3d8e023">
