### ISSUE TITLE
Revisit Node Runtime - Console Logging

### ISSUE THREAD

**Issue by JakeAi** [open-runtimes/open-runtimes#192]
The current revision only supports messages or objects and doesn't follow the original console functions.
Rather than introducing breaking changes and less functionality, just patch the original function properly especially since appwrite is reading the result from x-open-runtimes-logs. It doesn't make sense to remove the console functions when you can patch them to populate an array.

https://stackblitz.com/edit/stackblitz-starters-k1nhdj?file=index.js

**Comment by stnguyen90** [comment]
@JakeAi, unfortunately, replacing the built-in console.log caused too many problems:

1. unable to use console.log to actually write to stdout (and see the result in the docker logs)
2. unexpected behavior with logging objects
3. logs being mixed up in the wrong execution when executed concurrently

As such, we've decided to properly scope the logger.

**Comment by JakeAi** [comment]
I’m not sure you read my code and the current implementation.

**Comment by JakeAi** [comment]
@stnguyen90 all you are doing is piping the messages to a res header. There is no reason you can't patch the console functions to populate that header.
