### ISSUE TITLE
NodeJS ESM Support

### ISSUE THREAD

**Issue by tripolskypetr** [open-runtimes/open-runtimes#193]
Several weeks ago I started a new project build on top of [AppWrite Cloud](https://appwrite.io). As you can see, AppWrite has no support for any compiled language in cloud and [have no plan to support It](https://github.com/appwrite/appwrite/issues/6131). 

![image](https://github.com/open-runtimes/open-runtimes/assets/19227776/81ec3c18-d963-4e3c-ac03-7fe1a9955866)

Runtime versions are pretty outdated too. I got a situation, It my business case the python 3.9 runtime is 10–60% slower than 3.11. So I need to speed up my code

![image](https://github.com/open-runtimes/open-runtimes/assets/19227776/4048bc09-50fd-4244-8428-f32b093796d3)

To speedup It I can [convert](https://www.codeconvert.ai/python-to-javascript-converter) my python code to [AssemblyScript](https://www.assemblyscript.org/)

```javascript
async function instantiate(module, imports = {}) {
  const { exports } = await WebAssembly.instantiate(module, imports);
  return exports;
}
export const {
  memory,
  add,
} = await (async url => instantiate(
  await (async () => {
    try { return await globalThis.WebAssembly.compileStreaming(globalThis.fetch(url)); }
    catch { return globalThis.WebAssembly.compile(await (await import("node:fs/promises")).readFile(url)); }
  })(), {
  }
))(new URL("debug.wasm", import.meta.url));
```

The problem is AssemblyScript using ESM modules. The CommonJS [require statement can be created from ESM import](https://stackoverflow.com/questions/71884616/how-do-i-use-require-and-esm-import-in-the-same-project) statement

![image](https://github.com/open-runtimes/open-runtimes/assets/19227776/3b52015c-f568-49a8-96d9-af8370d46225)

The solution would be migrating from `commonjs` to `esm` modules in `server.js` in node runtime

~~`const fs = require("fs");`~~
~~`const micro = require("micro");`~~
~~`const util = require("util");`~~
~~`const { text: parseText, json: parseJson, send } = require("micro");`~~

```javascript
import fs from "fs";
import micro, { text as parseText, json: as parseJson, send } from "micro";
import util from "util";
```

To polyfill `require` statement I would recommend patching global object

```javascript
import Module from "node:module";
globalThis.require = Module.createRequire(import.meta.url);
```

**Comment by loks0n** [comment]
Hey @tripolskypetr, thanks for opening this issue!

ESM modules are supported in Open Runtimes v3 and Appwrite 1.4
Appwrite Cloud will be updated to 1.4 in the coming weeks.

As for enabling runtimes, we'd definitely can look at adding new runtimes once cloud is on 1.4.

**Comment by liudonghua123** [comment]
Yes, I found the esm implementation is [here](https://github.com/open-runtimes/open-runtimes/commit/3b102dd03099fb65821510023ce89c5a6d43d427#diff-9c3fa81cd9e5e2195bbc80ae1f8933dc26145c614fce4a10b3034e653552be1c) from the initial commit.

https://github.com/open-runtimes/open-runtimes/blob/3b102dd03099fb65821510023ce89c5a6d43d427/runtimes/node-16.0/src/server.js#L121-L129
