### ISSUE TITLE
Support ES Modules

### ISSUE THREAD

**Issue by JakeAi** [open-runtimes/open-runtimes#63]
Instead of require, use import("path") or require("path").default. This will also allow webpack, typescript, and other bundling options. Typescript was technically supported in the previous functions implementation.

https://github.com/open-runtimes/open-runtimes/blob/main/runtimes/node-17.0/server.js#L25

**Comment by Meldiron** [comment]
My initial idea to support is to do: (pseudo code)
```
if userFunction.default
  response = userFunction.default()
else
  response = userFunction()
```

Ill investigate further.

**Comment by Meldiron** [comment]
A new version has been released and it includes this change 🥳  Can we close this issue? 😇
