### ISSUE TITLE
Update installation steps numbering in `CONTRIBUTING.md` file

### ISSUE THREAD

**Issue by devblin** [open-runtimes/open-runtimes#79]
There are 4 steps in installation section, but in [CONTRIBUTING.md](https://github.com/open-runtimes/open-runtimes/blob/main/CONTRIBUTING.md) numbering is invalid.
![image](https://user-images.githubusercontent.com/55559527/169837378-5dd72ab9-9dae-4689-ac92-68aee4e8b612.png)

I would like to submit PR for this issue 👍🏽 .

**Comment by eldadfux** [comment]
If you're still interested please let me know and I'll reopen this issue.
