### ISSUE TITLE
Website "https://open-runtimes.com/" gives ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by gregfr** [open-runtimes/open-runtimes#80]
Greetings

When I try to connect to the website `https://open-runtimes.com` I have an error `ERR_CONNECTION_REFUSED`.

Is that only for me?

Regards

**Comment by eldadfux** [comment]
The website is still not up yet, we just own the domain.

**Comment by stnguyen90** [comment]
@eldadfux, it is a little weird to link our repo to a site that doesn't exist though. Perhaps we can have some sort of landing page? Or redirect it back to https://github.com/open-runtimes

**Comment by eldadfux** [comment]
@stnguyen90 agree, removed the link for now.
